CREATE TABLE `test_db`.`tbl_4` (
  `TBL2_Id` INT NOT NULL AUTO_INCREMENT,
  `TBL2_Name` VARCHAR(255) NULL,
  `TBL2_Ph_No` VARCHAR(255) NULL,
  PRIMARY KEY (`TBL2_Id`),
  UNIQUE INDEX `TBL2_Id_UNIQUE` (`TBL2_Id` ASC) VISIBLE);